services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mc
      POSTGRES_PASSWORD: "1122"
      POSTGRES_DB: chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: